Handle expected failure of @lavamoat/preinstall-always-fail package

diff --git a/.github/workflows/build-lint.yml b/.github/workflows/build-lint.yml
--- a/.github/workflows/build-lint.yml
+++ b/.github/workflows/build-lint.yml
@@ -22,7 +22,15 @@ jobs:
           node-version: ${{ matrix.node-version }}
       - name: Set Yarn version to 4.3.0
         run: yarn set version 4.3.0
-      - run: yarn install --immutable || true
+      - name: Install dependencies
+        run: |
+          yarn install --immutable || {
+            if grep -q '@lavamoat/preinstall-always-fail' /tmp/xfs-*/build.log; then
+              echo "Ignoring expected failure of @lavamoat/preinstall-always-fail"
+            else
+              exit 1
+            fi
+          }
       - run: yarn allow-scripts
       - run: yarn lint
       - name: Ensure demo build script works
